### ISSUE TITLE
영어 자동 줄바꿈시 자동개행 문제

### ISSUE THREAD

**Issue by Silica96** [zn/TweetDeckPlayer#2]
![asdasd](https://user-images.githubusercontent.com/9061758/50043769-75ff5f00-00bd-11e9-87a5-c26e37f9057d.PNG)

위 사진처럼 영어(숫자)를 친다음 앞쪽에 한글을 삽입했을때 스페이스를 누르면 앞에 개행문자가 자동으로 들어가는거 같네요 

사용 환경은 윈도우10, 사용버전 v2.34.1-G12-win32-x64입니다

**Comment by gaeulbyul** [comment]
안녕하세요, 새 버전으로 내려받아서 테스트해주실 수 있나요? https://repo.yona.io/gaeulbyul/TweetDeckPlayer/posts

**Comment by Silica96** [comment]
오류 없이 아주 잘 작동됩니다!

**Comment by gaeulbyul** [comment]
확인 감사합니다!
