### ISSUE TITLE
애플 실리콘 (혹은 맥 머신) 지원

### ISSUE THREAD

**Issue by JUSTIVE** [zn/TweetDeckPlayer#8]
안녕하세요, 트윗덱 플레이어를 윈도우 머신에서 매우 애용하고 있는 사용자 입니다.

맥 머신에서는 브라우저로 트윗덱을 사용하고 있는데, 트윗덱 브라우저에서만 제공하는 기능들이 많이 아쉬운 상황입니다.
이에 맥 디바이스의 지원이나, 애플 실리콘의 지원을 부탁드려도 될까요?
혹은 제가 개발을 진행한다면 맥 디바이스로의 빌드를 구축하는 데에 기존에 있던 어려움이 있을까요? 

다시 한번 위의 프로젝트를 만들어 주셔서 감사드립니다.

**Comment by gaeulbyul** [comment]
안녕하세요,
제가 현재 윈도우즈머신만 있고 macOS머신이 하나도 없다보니(...) 그 쪽으론 손대지 못하고 있습니다...
아마 Electron만 업데이트하면 그럭저럭 될 거 같긴 한데, 저로선 macOS상에서의 테스트도 빌드도 못 하는 상황이라 장담은 못하겠네요... 😅

**Comment by JUSTIVE** [comment]
아하.. 일단 어떻게든 패키징은 했는데 혹시 이 바이너리 메일로 공유드리면 될까요?

**Comment by JUSTIVE** [comment]
헉 그런데 제가 꼭 필요했던 클립보드 이미지 붙이기가 안되네요..

**Comment by gaeulbyul** [comment]
패키지는 제게 보내주시면 업로드하도록 할게요.
~~그리구 클립보드는.. 그게 윈도우즈 기준으로 만들다보니 Ctrl키로 되어있습니다. Cmd+V를 하시려면 수정해야 할거에요..~~

**Comment by JUSTIVE** [comment]
클립보드 복사와 관련해서 Ctrl/Cmd 관련한 코드가 보이진 않네요 ㅠㅠ...

**Comment by gaeulbyul** [comment]
으악 죄송합니다 제가 착각했어요....ㅠㅠ 죄송...

**Comment by JUSTIVE** [comment]
엄.. 메일을 ben399399@gmail.com으로 알려주시겠어요? 메일편으로 파일을 보내드리려 했는데 메일을 못찾겠네요 ㅠㅠ

**Comment by gaeulbyul** [comment]
업로드 완료했습니다. https://repo.yona.io/gaeulbyul/TweetDeckPlayer/post/23
